apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostinfo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hostinfo
  template:
    metadata:
      labels:
        app: hostinfo
    spec:
      containers:
        - name: hostinfo
          image: pascalgn/hostinfo
          env:
            - name: HOSTINFO_PORT
              value: "5000"
          ports:
            - containerPort: 5000
              name: hostinfo-port
---
apiVersion: v1
kind: Service
metadata:
  name: hostinfo
  labels:
    app: hostinfo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: hostinfo-port
      name: hostinfo-service-port
  selector:
    app: hostinfo
